# Generated by Django 3.2.2 on 2021-05-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabe',
            new_name='available',
        ),
    ]
